name: Generate LOC Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full Git history is available

      - name: Run Elocuent
        run: |
          npx elocuent -d . -o meta/loc.csv

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p meta
          git pull
          git add -f meta/loc.csv
          git commit -m "Update code statistics" || echo "No changes to commit"
          git push
